#pragma once
#include <Arduino.h>
#include "Core.h"

namespace sumi {

// Drain all pending button events on activity/state entry.
// Prevents power-button-wake from leaking into page turns,
// and long-press holds from triggering actions in the new state.
//
// Usage: call at the top of enter() in any state that suffers
// from leaked button presses.
//   InputDrainGuard::drain(core);
struct InputDrainGuard {
  static void drain(Core& core) {
    // Drain all queued events
    core.events.clear();

    // Wait until all physical buttons are released (up to 500 ms)
    const unsigned long deadline = millis() + 500;
    while (millis() < deadline) {
      core.input.poll();
      if (!anyHeld(core)) break;
      delay(10);
    }

    // Drain any events generated by the polling above
    core.events.clear();
  }

private:
  static bool anyHeld(Core& core) {
    return core.input.isPressed(Button::Up)
        || core.input.isPressed(Button::Down)
        || core.input.isPressed(Button::Left)
        || core.input.isPressed(Button::Right)
        || core.input.isPressed(Button::Center)
        || core.input.isPressed(Button::Back)
        || core.input.isPressed(Button::Power);
  }
};

}  // namespace sumi
