import gzip
import os
import re
import secrets

SRC_DIR = "src"

# Known limitations of this minifier (audit #51). For SUMI's curated
# single-doc use these are theoretical, but if you reuse this script
# for a less controlled corpus, audit accordingly:
#
#   1. The non-greedy `<script>...</script>` regex matches up to the
#      first `</script>` literal it sees. JavaScript that contains
#      `"</script>"` as a *string* will terminate early. Workaround:
#      write `"<\/script>"` in any such string, OR move that script
#      to an external .js file.
#
#   2. The `\s+` collapse-whitespace pass runs on the whole document
#      (after preserve-block extraction) and will collapse repeated
#      spaces inside attribute values: `alt="My  Photo"` becomes
#      `alt="My Photo"`. Usually fine, sometimes meaningful. If it
#      matters, embed the value as a Unicode non-breaking space or
#      use a `<title>` tooltip instead.
#
#   3. Placeholder collision (audit #51 fix below): the protect-and-
#      restore round-trip used a deterministic `__PRESERVE_BLOCK_N__`
#      sentinel, which would collide if an HTML literal happened to
#      contain that exact token. We now mix in a per-run random
#      hex prefix (`secrets.token_hex(8)`) so collision is effectively
#      impossible.

def minify_html(html: str) -> str:
    # Tags where whitespace should be preserved
    preserve_tags = ['pre', 'code', 'textarea', 'script', 'style']
    preserve_regex = '|'.join(preserve_tags)

    # Per-run random sentinel — eliminates the audit's collision case.
    placeholder_token = f"__PRESERVE_BLOCK_{secrets.token_hex(8)}__"

    # Protect preserve blocks with placeholders
    preserve_blocks = []
    def preserve(match):
        preserve_blocks.append(match.group(0))
        return f"{placeholder_token}_{len(preserve_blocks)-1}__"

    html = re.sub(rf'<({preserve_regex})[\s\S]*?</\1>', preserve, html, flags=re.IGNORECASE)

    # Remove HTML comments
    html = re.sub(r'<!--.*?-->', '', html, flags=re.DOTALL)

    # Collapse all whitespace between tags
    html = re.sub(r'>\s+<', '><', html)

    # Collapse multiple spaces inside tags
    html = re.sub(r'\s+', ' ', html)

    # Restore preserved blocks
    for i, block in enumerate(preserve_blocks):
        html = html.replace(f"{placeholder_token}_{i}__", block)

    return html.strip()

for root, _, files in os.walk(SRC_DIR):
    for file in files:
        if file.endswith(".html"):
            html_path = os.path.join(root, file)
            with open(html_path, "r", encoding="utf-8") as f:
                html_content = f.read()

            minified = minify_html(html_content)
            compressed = gzip.compress(minified.encode('utf-8'), compresslevel=9)
            base_name = f"{os.path.splitext(file)[0]}Html"
            header_path = os.path.join(root, f"{base_name}.generated.h")

            with open(header_path, "w", encoding="utf-8") as h:
                h.write("// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
                h.write("#pragma once\n\n")
                h.write("#include <cstddef>\n\n")
                h.write(f"constexpr char {base_name}[] PROGMEM = {{\n")
                for i in range(0, len(compressed), 16):
                    chunk = compressed[i:i+16]
                    hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
                    h.write(f"    {hex_vals},\n")
                h.write("};\n")
                h.write(f"constexpr size_t {base_name}CompressedSize = sizeof({base_name});\n")

            original_size = len(html_content)
            minified_size = len(minified.encode('utf-8'))
            compressed_size = len(compressed)
            print(f"Generated: {header_path} ({original_size} → {minified_size} → {compressed_size} bytes)")
