#pragma once

// =============================================================================
// Feature Flags (set via platformio.ini build_flags)
// =============================================================================
#ifndef FEATURE_PLUGINS
#define FEATURE_PLUGINS 1
#endif

#ifndef FEATURE_BLUETOOTH
#define FEATURE_BLUETOOTH 1
#endif

#ifndef FEATURE_GAMES
#define FEATURE_GAMES 1
#endif

#ifndef FEATURE_FLASHCARDS
#define FEATURE_FLASHCARDS 1
#endif

// Font IDs (audit #54).
//
// These are committed-in literal values, not auto-generated. They're
// used as the cache-key for /.sumi/cache/<book>/pages_<fontId>.bin —
// changing them invalidates every existing user's EPUB cache and
// forces a full re-parse on next reader open (10-30s per long book).
//
// To detect drift between these literals and the actual font binaries
// in lib/EpdFont/builtinFonts/, every build runs
// scripts/check_font_ids.py — it computes the binary-derived IDs and
// logs a warning if any differ from the literals below. The warning
// is informational only; it does NOT update config.h.
//
// To intentionally regenerate (e.g. after deliberately updating a
// font binary AND accepting the one-time cache invalidation cost):
//   python scripts/check_font_ids.py --regenerate
// then commit src/config.h with the new IDs. Document the cache-
// invalidation in release notes.
//
// Pre-Batch-9-followup these were generated by a Ruby snippet
// embedded in comments here. The snippet (preserved in
// scripts/check_font_ids.py's docstring) is the authoritative
// algorithm.
#define READER_FONT_ID_XSMALL (-1506109732)
#define READER_FONT_ID 1818981670
#define READER_FONT_ID_MEDIUM (-455101320)
#define READER_FONT_ID_LARGE 1922188069
#define UI_FONT_ID (-731562571)
#define SMALL_FONT_ID 1482513144

// System directory for settings and cache
#define SUMI_DIR "/.sumi"
#define SUMI_CACHE_DIR SUMI_DIR "/cache"
#define SUMI_SETTINGS_FILE SUMI_DIR "/settings.bin"
#define SUMI_STATE_FILE SUMI_DIR "/state.bin"

// Thumbnail dimensions for home screen
#define THUMB_WIDTH 320
#define THUMB_HEIGHT 440

// User configuration directory
#define CONFIG_DIR "/config"
#define CONFIG_THEMES_DIR CONFIG_DIR "/themes"
#define CONFIG_FONTS_DIR CONFIG_DIR "/fonts"

// Applies custom theme fonts for the currently selected font size.
// Call this after font size or theme changes to reload fonts.
void applyThemeFonts();

// =============================================================================
// Plugin System Paths
// =============================================================================
#if FEATURE_PLUGINS
#define PLUGINS_CUSTOM_DIR "/custom"
#define PLUGINS_NOTES_DIR "/notes"
#define PLUGINS_FLASHCARDS_DIR "/flashcards"
#define PLUGINS_IMAGES_DIR "/images"
#define PLUGINS_MAPS_DIR "/maps"
#define PLUGINS_GAMES_DIR "/games"
#endif
